print("Program starting")
Color = input("Insert hex color:  ").strip()
RGB =("RED, GREEN, BLUE")
Red = input(Color[:3])
Green =input(Color[3:5])
Blue =input(Color[5:7])
print(f"{Red[:3]}")  
print(f"{Green[3:5]}")  
print(f"{Blue[5:7]}")
print("Program ending")