print ("Program starting.")
A1 = int(input("A1_T1: "))
A2 = int(input("A1_T2: "))
A3 = int(input("A1_T3: "))
A4  = int(input("A1_T4: "))
A5  = int(input("A1_T5: "))
A6  = int(input("A1_T6: "))
A7  = int(input("A1_T7: "))

Total = (A1) + (A2) + (A3) + (A4) + (A5) + (A6) + (A7)
Mean = (Total /7  )
r = round(Mean) 

print (f"The average time you spend for each task is {r}")
print("program ending")