print("Program starting")
Firstword = (input("Insert first word: "))
Secondword =(input("Insert second word: "))
len1 = len (Firstword)
len2 = len (Secondword)
print (f" 1st word is {len1} characters long.")
print (f" 2nd word is {len2} characters long.")
print("Words together makes one closed compound 'firefighter' ")
print("Program ending.")